steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - gcr.io/tam-aaron-hubbart/daily-brief-viewer:latest
      - -f
      - webapp/Dockerfile
      - .
    dir: viewer

  - name: gcr.io/cloud-builders/docker
    args: [push, gcr.io/tam-aaron-hubbart/daily-brief-viewer:latest]

options:
  logging: CLOUD_LOGGING_ONLY
