import express, { Request, Response } from "express";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";
import {
  BriefItemSchema,
  upsertItem,
  batchUpsertItems,
  AccountProjectSchema,
  syncAccountProjects,
  DailyBriefApiError
} from "./dailyBriefClient.js";
import { requestContext } from "./requestContext.js";

const server = new McpServer({
  name: "daily-brief-mcp-server",
  version: "1.0.0"
});

// --- daily_brief_upsert_item -------------------------------------------------

const UpsertItemInputSchema = z.object({
  brief_date: z.string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Must be YYYY-MM-DD")
    .describe("The brief's date, e.g. '2026-07-20'"),
  item: BriefItemSchema.describe("The single item to create or update")
}).strict();

type UpsertItemInput = z.infer<typeof UpsertItemInputSchema>;

server.registerTool(
  "daily_brief_upsert_item",
  {
    title: "Upsert a single daily-brief item",
    description: `Create or update one item in the daily-brief viewer's Postgres store.

Use this for out-of-band patches: post-meeting-patch runs, section-refresh runs, or any
single-item update. For a full brief run with many items, use daily_brief_batch_upsert_items
instead — one call per item is much slower for a whole day's worth of items.

The (brief_date, section, item_key) triple is the natural key. Upserting with the same
key updates the existing row instead of creating a duplicate; there is no separate
"update" tool.

Args:
  - brief_date (string): YYYY-MM-DD
  - item (object): section, item_key, item_type, and the relevant title/subtitle/badge/links/content/checked/display_order fields per the daily-brief skill's item-sync.md conventions

Returns:
  { "ok": true, "item_key": "<the key that was upserted>" }

Error Handling:
  - Returns "Error: daily-brief API returned 401" if the bearer token is invalid or expired
  - Returns "Error: daily-brief API returned 4xx/5xx" with the response body for other failures`,
    inputSchema: UpsertItemInputSchema,
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true
    }
  },
  async (params: UpsertItemInput) => {
    try {
      const result = await upsertItem(params.brief_date, params.item);
      return {
        content: [{ type: "text", text: JSON.stringify(result) }],
        structuredContent: result
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: formatError(err) }],
        isError: true
      };
    }
  }
);

// --- daily_brief_batch_upsert_items ------------------------------------------

const BatchUpsertInputSchema = z.object({
  brief_date: z.string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Must be YYYY-MM-DD")
    .describe("The brief's date, e.g. '2026-07-20'"),
  brief_type: z.enum(["morning", "midday", "evening"])
    .describe("Which brief run this is, used by the viewer to render the header"),
  items: z.array(BriefItemSchema)
    .min(1)
    .describe("All items generated by this brief run, across all 7 sections")
}).strict();

type BatchUpsertInput = z.infer<typeof BatchUpsertInputSchema>;

server.registerTool(
  "daily_brief_batch_upsert_items",
  {
    title: "Batch-upsert all items for a full daily-brief run",
    description: `Sync an entire brief run's items to the viewer's Postgres store in one call.

Use this at the end of a normal "brief me" run, after all sections (Yesterday's Meetings,
Account/Initiative Recap, Today, Action Items, FYI, Customer Updates, Manager Update) have
been generated. Each entry in items uses the same (brief_date, section, item_key) upsert
semantics as daily_brief_upsert_item — existing rows are updated in place, not duplicated.

Args:
  - brief_date (string): YYYY-MM-DD
  - brief_type ('morning' | 'midday' | 'evening')
  - items (array): every item across all sections for this run

Returns:
  { "ok": true, "count": <number of items upserted> }

Error Handling:
  - Returns "Error: daily-brief API returned 401" if the bearer token is invalid or expired
  - Returns "Error: daily-brief API returned 4xx/5xx" with the response body for other failures
  - A failed sync should not block the in-chat brief — treat this as best-effort and report
    the failure back to the person rather than retrying indefinitely`,
    inputSchema: BatchUpsertInputSchema,
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true
    }
  },
  async (params: BatchUpsertInput) => {
    try {
      const result = await batchUpsertItems(
        params.brief_date,
        params.brief_type,
        params.items
      );
      return {
        content: [{ type: "text", text: JSON.stringify(result) }],
        structuredContent: result
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: formatError(err) }],
        isError: true
      };
    }
  }
);

function formatError(err: unknown): string {
  if (err instanceof DailyBriefApiError) {
    return `Error: daily-brief API returned ${err.status} for this request. Body: ${err.body.slice(0, 500)}`;
  }
  if (err instanceof Error) {
    return `Error: ${err.message}`;
  }
  return `Error: ${String(err)}`;
}

// --- daily_brief_sync_account_projects ---------------------------------------

const SyncAccountProjectsInputSchema = z.object({
  accounts: z.array(AccountProjectSchema)
    .describe("The full current account -> Asana project GID mapping, read fresh from Meeting Manager Config.xlsx's Accounts sheet")
}).strict();

type SyncAccountProjectsInput = z.infer<typeof SyncAccountProjectsInputSchema>;

server.registerTool(
  "daily_brief_sync_account_projects",
  {
    title: "Sync the account -> Asana project GID mapping",
    description: `Mirrors the skill's account -> Asana project GID mapping (from Meeting Manager Config.xlsx) into the viewer's Postgres store, as a full replace for this user.

Call this once per brief run, after reading the Accounts sheet's Account Name and Asana Project GID columns. This is what the webapp reads to know which boards to poll for its live Overdue/Due Next 7 Days/No Due Date Action Items pull — the webapp has no Google Drive access of its own, so it can't read the sheet directly.

This is a full replace, not a merge: send every account currently in the sheet with a non-blank Asana Project GID on every call, even ones that haven't changed. Omitting an account here removes its mapping — do not send only the accounts that changed since the last run.

Args:
  - accounts (array of {account_name, project_gid}): every account with a configured GID

Returns:
  { "ok": true, "count": <number of accounts synced> }

Error Handling:
  - Returns "Error: daily-brief API returned 401" if the bearer token is invalid or expired
  - A failed sync should not block the in-chat brief — treat this as best-effort, same as the item upserts`,
    inputSchema: SyncAccountProjectsInputSchema,
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true
    }
  },
  async (params: SyncAccountProjectsInput) => {
    try {
      const result = await syncAccountProjects(params.accounts);
      return {
        content: [{ type: "text", text: JSON.stringify(result) }],
        structuredContent: result
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: formatError(err) }],
        isError: true
      };
    }
  }
);

// --- HTTP transport + auth ----------------------------------------------------
//
// Auth model: per-user passthrough, not a shared secret. Each person adds this
// connector in their own Claude account and supplies their OWN daily-brief API
// token (from $DAILY_BRIEF_API_BASE_URL/api/token, after signing in with their
// own Azure AD account) as the connector's static header credential. This
// server holds no secret of its own — it only requires that *some* bearer
// token is present, then forwards that exact value to the webapp API for
// every call in this request (see requestContext.ts / dailyBriefClient.ts).
// The webapp's existing per-user token check (db.get_user_by_token) is the
// real auth boundary; this server is a thin pass-through in front of it.
//
// This intentionally replaces the old single MCP_SHARED_SECRET model, where
// every user shared one server-wide credential and all synced items landed
// under whichever single webapp account that credential's DAILY_BRIEF_API_TOKEN
// belonged to. A leaked token now only exposes the one person it belongs to,
// not everyone using this connector.

const app = express();
app.use(express.json());

app.get("/healthz", (_req: Request, res: Response) => {
  res.status(200).send("ok");
});

app.post("/mcp", async (req: Request, res: Response) => {
  const authHeader = req.header("authorization") ?? "";
  const match = authHeader.match(/^Bearer (.+)$/);
  if (!match) {
    res.status(401).json({ error: "Missing bearer token. Add your own daily-brief API token as this connector's Authorization header — see README.md." });
    return;
  }
  const token = match[1];

  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
    enableJsonResponse: true
  });
  res.on("close", () => transport.close());

  await requestContext.run({ token }, async () => {
    await server.connect(transport);
    await transport.handleRequest(req, res, req.body);
  });
});

const port = parseInt(process.env.PORT || "3000", 10);
app.listen(port, () => {
  console.error(`daily-brief-mcp-server listening on :${port}/mcp`);
});
