import express, { Request, Response } from "express";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";
import {
  BriefItemSchema,
  upsertItem,
  batchUpsertItems,
  DailyBriefApiError
} from "./dailyBriefClient.js";

const server = new McpServer({
  name: "daily-brief-mcp-server",
  version: "1.0.0"
});

// --- daily_brief_upsert_item -------------------------------------------------

const UpsertItemInputSchema = z.object({
  brief_date: z.string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Must be YYYY-MM-DD")
    .describe("The brief's date, e.g. '2026-07-20'"),
  item: BriefItemSchema.describe("The single item to create or update")
}).strict();

type UpsertItemInput = z.infer<typeof UpsertItemInputSchema>;

server.registerTool(
  "daily_brief_upsert_item",
  {
    title: "Upsert a single daily-brief item",
    description: `Create or update one item in the daily-brief viewer's Postgres store.

Use this for out-of-band patches: post-meeting-patch runs, section-refresh runs, or any
single-item update. For a full brief run with many items, use daily_brief_batch_upsert_items
instead — one call per item is much slower for a whole day's worth of items.

The (brief_date, section, item_key) triple is the natural key. Upserting with the same
key updates the existing row instead of creating a duplicate; there is no separate
"update" tool.

Args:
  - brief_date (string): YYYY-MM-DD
  - item (object): section, item_key, item_type, and the relevant title/subtitle/badge/links/content/checked/display_order fields per the daily-brief skill's item-sync.md conventions

Returns:
  { "ok": true, "item_key": "<the key that was upserted>" }

Error Handling:
  - Returns "Error: daily-brief API returned 401" if the bearer token is invalid or expired
  - Returns "Error: daily-brief API returned 4xx/5xx" with the response body for other failures`,
    inputSchema: UpsertItemInputSchema,
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true
    }
  },
  async (params: UpsertItemInput) => {
    try {
      const result = await upsertItem(params.brief_date, params.item);
      return {
        content: [{ type: "text", text: JSON.stringify(result) }],
        structuredContent: result
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: formatError(err) }],
        isError: true
      };
    }
  }
);

// --- daily_brief_batch_upsert_items ------------------------------------------

const BatchUpsertInputSchema = z.object({
  brief_date: z.string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Must be YYYY-MM-DD")
    .describe("The brief's date, e.g. '2026-07-20'"),
  brief_type: z.enum(["morning", "midday", "evening"])
    .describe("Which brief run this is, used by the viewer to render the header"),
  items: z.array(BriefItemSchema)
    .min(1)
    .describe("All items generated by this brief run, across all 7 sections")
}).strict();

type BatchUpsertInput = z.infer<typeof BatchUpsertInputSchema>;

server.registerTool(
  "daily_brief_batch_upsert_items",
  {
    title: "Batch-upsert all items for a full daily-brief run",
    description: `Sync an entire brief run's items to the viewer's Postgres store in one call.

Use this at the end of a normal "brief me" run, after all sections (Yesterday's Meetings,
Account/Initiative Recap, Today, Action Items, FYI, Customer Updates, Manager Update) have
been generated. Each entry in items uses the same (brief_date, section, item_key) upsert
semantics as daily_brief_upsert_item — existing rows are updated in place, not duplicated.

Args:
  - brief_date (string): YYYY-MM-DD
  - brief_type ('morning' | 'midday' | 'evening')
  - items (array): every item across all sections for this run

Returns:
  { "ok": true, "count": <number of items upserted> }

Error Handling:
  - Returns "Error: daily-brief API returned 401" if the bearer token is invalid or expired
  - Returns "Error: daily-brief API returned 4xx/5xx" with the response body for other failures
  - A failed sync should not block the in-chat brief — treat this as best-effort and report
    the failure back to the person rather than retrying indefinitely`,
    inputSchema: BatchUpsertInputSchema,
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true
    }
  },
  async (params: BatchUpsertInput) => {
    try {
      const result = await batchUpsertItems(
        params.brief_date,
        params.brief_type,
        params.items
      );
      return {
        content: [{ type: "text", text: JSON.stringify(result) }],
        structuredContent: result
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: formatError(err) }],
        isError: true
      };
    }
  }
);

function formatError(err: unknown): string {
  if (err instanceof DailyBriefApiError) {
    return `Error: daily-brief API returned ${err.status} for this request. Body: ${err.body.slice(0, 500)}`;
  }
  if (err instanceof Error) {
    return `Error: ${err.message}`;
  }
  return `Error: ${String(err)}`;
}

// --- HTTP transport + auth ----------------------------------------------------
//
// Auth model: this server expects Claude to attach a fixed bearer token on every
// request (the "static_headers" auth type — see docs.claude.com/docs/connectors/
// building/authentication). The check below is a defense-in-depth measure in case
// the server URL leaks; it is NOT a substitute for keeping the URL and token private,
// and it is NOT full OAuth. If your org needs per-user auth/consent instead of one
// shared secret, implement the OAuth flow described in that same doc rather than
// relying on this shared-secret check.

const CONNECTOR_SHARED_SECRET = process.env.MCP_SHARED_SECRET;

const app = express();
app.use(express.json());

app.get("/healthz", (_req: Request, res: Response) => {
  res.status(200).send("ok");
});

app.post("/mcp", async (req: Request, res: Response) => {
  if (CONNECTOR_SHARED_SECRET) {
    const authHeader = req.header("authorization") ?? "";
    if (authHeader !== `Bearer ${CONNECTOR_SHARED_SECRET}`) {
      res.status(401).json({ error: "unauthorized" });
      return;
    }
  }

  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
    enableJsonResponse: true
  });
  res.on("close", () => transport.close());
  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
});

const port = parseInt(process.env.PORT || "3000", 10);
app.listen(port, () => {
  console.error(`daily-brief-mcp-server listening on :${port}/mcp`);
});
